# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('answers', '0002_answer_messagetemplateid'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_surname', models.CharField(max_length=200)),
                ('user_position', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_login', models.CharField(max_length=200)),
                ('user_mail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserToAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.User')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='answers.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='UserToChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='users.User')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chats.Chat')),
            ],
        ),
    ]
