# Generated by Django 2.0.1 on 2018-02-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tasks.Task')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.User')),
            ],
        ),
    ]
