# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=200)),
                ('link_adress', models.TextField()),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='events.Event')),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tasks.Task')),
            ],
        ),
    ]
